# Generated by Django 4.2.7 on 2023-12-19 13:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import trascendence.api.models.Interactions
import trascendence.api.models.SerializableModel
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_pair_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_pair_1', to='api.usermodel')),
                ('user_pair_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_pair_2', to='api.usermodel')),
            ],
            bases=(models.Model, trascendence.api.models.SerializableModel.SerializableModel),
        ),
        migrations.CreateModel(
            name='FriendInvitation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invite_code', models.CharField(default=trascendence.api.models.Interactions.id_generator, max_length=6)),
                ('note', models.CharField(max_length=400)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_origin', to='api.usermodel')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_target', to='api.usermodel')),
            ],
            bases=(models.Model, trascendence.api.models.SerializableModel.SerializableModel),
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_issuer', to='api.usermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to='api.usermodel')),
            ],
            bases=(models.Model, trascendence.api.models.SerializableModel.SerializableModel),
        ),
    ]
