# Generated by Django 4.2.7 on 2023-12-13 15:52

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.CharField(default=uuid.UUID('64a1a89e-e727-43c5-982e-7514fe407910'), max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('intraId', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('avatarURI', models.CharField(max_length=200)),
            ],
        ),
    ]
