# Generated by Django 4.2.7 on 2024-01-15 13:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import trascendence.api.models.SerializableModel
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('intraId', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('avatarURI', models.CharField(max_length=200)),
            ],
            bases=(models.Model, trascendence.api.models.SerializableModel.SerializableModel),
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tournament_name', models.CharField(max_length=50)),
                ('tournament_code', models.CharField(default='Z8QLYIPS', max_length=8)),
                ('players_capacity', models.IntegerField(default=8, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(4)])),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_user', to='api.usermodel')),
            ],
            bases=(models.Model, trascendence.api.models.SerializableModel.SerializableModel),
        ),
        migrations.CreateModel(
            name='TournamentPlayers',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tournament_id', to='api.tournaments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to='api.usermodel')),
            ],
            bases=(models.Model, trascendence.api.models.SerializableModel.SerializableModel),
        ),
        migrations.CreateModel(
            name='TournamentInvitations',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=400)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_target_user', to='api.usermodel')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tournament_id', to='api.tournaments')),
            ],
            bases=(models.Model, trascendence.api.models.SerializableModel.SerializableModel),
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('winner', models.CharField(choices=[('h', 'home'), ('a', 'away'), ('u', 'unknown')], default='u', max_length=1)),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_away', to='api.usermodel')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_home', to='api.usermodel')),
            ],
            bases=(models.Model, trascendence.api.models.SerializableModel.SerializableModel),
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_pair_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_pair_1', to='api.usermodel')),
                ('user_pair_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_pair_2', to='api.usermodel')),
            ],
            bases=(models.Model, trascendence.api.models.SerializableModel.SerializableModel),
        ),
        migrations.CreateModel(
            name='FriendInvitation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invite_code', models.CharField(default='VX8RSH', max_length=6)),
                ('note', models.CharField(max_length=400)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_origin', to='api.usermodel')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_target', to='api.usermodel')),
            ],
            bases=(models.Model, trascendence.api.models.SerializableModel.SerializableModel),
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_issuer', to='api.usermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to='api.usermodel')),
            ],
            bases=(models.Model, trascendence.api.models.SerializableModel.SerializableModel),
        ),
    ]
