# Generated by Django 4.2.7 on 2024-01-15 13:54

from django.db import migrations, models
import trascendence.api.models.shared_functions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendinvitation',
            name='invite_code',
            field=models.CharField(default=trascendence.api.models.shared_functions.id_generator, max_length=6),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='tournament_code',
            field=models.CharField(default=trascendence.api.models.shared_functions.id_generator, max_length=8),
        ),
    ]
