# Generated by Django 4.2.7 on 2024-01-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayers',
            name='has_pair',
            field=models.BooleanField(default=False),
        ),
    ]
