# Generated by Django 4.2.7 on 2023-12-13 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.CharField(default=uuid.UUID('f383c8ca-5f40-477d-95a7-d5fe4aab3834'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
