# Generated by Django 4.2.7 on 2024-01-22 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tournamentplayers_has_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayers',
            name='pair_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_pair_user', to='api.usermodel'),
        ),
    ]
