# Generated by Django 4.2.7 on 2024-01-21 13:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import trascendence.api.models.SerializableModel
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tournaments_tournament_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tournament_id', to='api.tournaments'),
        ),
        migrations.CreateModel(
            name='TournamentMatches',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('match_priority', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_match_id', to='api.matches')),
            ],
            bases=(models.Model, trascendence.api.models.SerializableModel.SerializableModel),
        ),
    ]
