# Generated by Django 4.2.7 on 2023-12-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usermodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='updated_at',
        ),
    ]
