# Generated by Django 4.2.7 on 2024-01-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tournamentplayer_delete_tournamentplayers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TournamentPlayer',
            new_name='TournamentPlayers',
        ),
    ]
