# Generated by Django 5.0.2 on 2024-02-20 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='name',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
