# Generated by Django 5.0.2 on 2024-02-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_uploads_created_at_alter_uploads_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(blank=True, max_length=72, null=True),
        ),
    ]
