# Generated by Django 5.0.2 on 2024-02-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_usermodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='intra_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_active',
            field=models.BooleanField(default=True),
        ),
    ]
