# Generated by Django 5.0.2 on 2024-02-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_usermodel_intra_login_usermodel_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='intraId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
