# Generated by Django 5.0.2 on 2024-02-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_usermodel_intraid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default='John', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='surname',
            field=models.CharField(default='Doe', max_length=50),
            preserve_default=False,
        ),
    ]
